-- Drop tables
DROP VIEW IF EXISTS CourseAverageScores;
DROP TABLE IF EXISTS CompletedCourses;
DROP TABLE IF EXISTS StudentReview;
DROP TABLE IF EXISTS CourseBlock;
DROP TABLE IF EXISTS CourseExamType;
DROP TABLE IF EXISTS CourseProfessor;
DROP TABLE IF EXISTS CourseResult;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS CoursePrerequisite;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Professor;
DROP TABLE IF EXISTS ExamType;
DROP TABLE IF EXISTS Block;
